# Generated by Django 5.1 on 2024-09-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('To Read', 'To Read'), ('Reading', 'Reading'), ('Finished', 'Finished')], default='To Read', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
