# Generated by Django 5.1 on 2024-09-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_category_mediaitem_delete_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='cover_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='status',
            field=models.CharField(choices=[('To Read', 'To Read'), ('Reading', 'Reading'), ('Finished', 'Finished'), ('Watching', 'Watching'), ('Completed', 'Completed'), ('On Hold', 'On Hold')], default='To Read', max_length=20),
        ),
        migrations.CreateModel(
            name='CustomList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('items', models.ManyToManyField(blank=True, to='books.mediaitem')),
            ],
        ),
    ]
