# Generated by Django 5.1 on 2024-09-07 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_mediaitem_cover_url_alter_mediaitem_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customlist',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='custom_lists', to='books.category'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='status',
            field=models.CharField(choices=[('To Read', 'To Read'), ('Reading', 'Reading'), ('Finished', 'Finished'), ('To Watch', 'To Watch'), ('Watching', 'Watching'), ('Completed', 'Completed'), ('On Hold', 'On Hold')], default='To Read', max_length=20),
        ),
    ]
