# Generated by Django 5.1 on 2024-09-12 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20240910_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaitem',
            options={'ordering': ['id']},
        ),
    ]
