# Generated by Django 5.1 on 2024-09-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_mediaitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customlist',
            name='background_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
